# Factories generated by Factory Girl Ruby gem
# By putting the factories.rb file in the spec/ directory
# we arrange for RSpec to load our factories automatically whenever the tests run.
# Factories bypass attr_accessible so they can use mass assignment.

# User factory to simulate User model objects
# By using the symbol ':user', we get Factory Girl to simulate the User model.
Factory.define :user do |user|
  user.name                   "Chris Hilton"
  user.email                  "chris.hilton@insphire.com"
  user.password               "foobar"
  user.password_confirmation  "foobar"
end

# Factory sequence for email address
Factory.sequence :email do |n|
  "person-#{n}@example.com"
end

# Factory for micropost
# using Factory Girl method association to associate micropost with user
Factory.define :micropost do |micropost|
  micropost.content "Foo bar"
  micropost.association :user
end

