# Factories generated by Factory Girl Ruby gem
# By putting the factories.rb file in the spec/ directory
# we arrange for RSpec to load our factories automatically whenever the tests run.

# User factory to simulate User model objects
Factory.define :user do |user|
  user.name                   "Chris Hilton"
  user.email                  "chris.hilton@insphire.com"
  user.password               "foobar"
  user.password_confirmation  "foobar"
end
